site_name: Specctl
docs_dir: 'docs/'
copyright: 'Copyright &copy; Amazon 2023'
site_author: 'AWS'
site_url: 'https://awslabs.github.io/specctl'
repo_name: 'specctl'
repo_url: 'https://github.com/awslabs/specctl'
nav:
  - Quick Start: index.md
  - Kubernetes to ECS Fargate: k8s2ecs.md
  - ECS to Kubernetes: ecs2k8s.md
  - Docker Compose to Kubernetes: dc2k8s.md

theme:
  name: material
  logo: images/white-logo.png
  favicon: images/colored-logo.png
  font:
    text: ember
  palette:
    primary: orange
    accent: orange
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs.sticky
  highlightjs: true
  hljs_languages:
    - yaml
    - json

plugins:
  - include-markdown